import type { VariableDefinition } from "@modules/email/email.types.js";

export const ABSTRACT_EMAIL_VARIABLES: VariableDefinition[] = [
  {
    id: "authorName",
    label: "Author Name",
    category: "abstract",
    description: "First and last name of the submitting author",
    example: "Dr. Ahmed Salah",
  },
  {
    id: "submissionTitle",
    label: "Submission Title",
    category: "abstract",
    description: "Title of the submitted abstract",
    example: "Novel Approaches to Cardiac Imaging",
  },
  {
    id: "submissionStatus",
    label: "Submission Status",
    category: "abstract",
    description: "Current status of the abstract in French",
    example: "Accepté",
  },
  {
    id: "presentationType",
    label: "Presentation Type",
    category: "abstract",
    description: "Requested or final presentation type in French",
    example: "Communication orale",
  },
  {
    id: "submissionCode",
    label: "Submission Code",
    category: "abstract",
    description: "Unique abstract code (assigned after review)",
    example: "AB-001",
  },
  {
    id: "committeeComments",
    label: "Committee Comments",
    category: "abstract",
    description: "Comments from the scientific committee (Phase IV)",
    example: "Please revise the methodology section.",
  },
  {
    id: "congressName",
    label: "Congress Name",
    category: "event",
    description: "Name of the event/congress",
    example: "Medical Conference 2025",
  },
  {
    id: "platformLink",
    label: "Platform Link",
    category: "links",
    description: "Link to the event on the submission platform",
    example: "https://events.example.com/medical-2025",
  },
  {
    id: "abstractEditLink",
    label: "Abstract Edit Link",
    category: "links",
    description: "Magic link for the author to view/edit their abstract",
    example: "https://events.example.com/medical-2025/abstracts/abc123/token123",
  },
  {
    id: "finalFileUploadLink",
    label: "Final File Upload Link",
    category: "links",
    description: "Magic link that lets accepted authors upload their final file",
    example: "https://events.example.com/medical-2025/abstracts/abc123/token123",
  },
  {
    id: "submissionStartAt",
    label: "Submission Opens",
    category: "event",
    description: "Date the abstract submission window opens",
    example: "March 1, 2026",
  },
  {
    id: "submissionDeadline",
    label: "Submission Deadline",
    category: "event",
    description: "Date the abstract submission window closes",
    example: "May 15, 2026",
  },
  {
    id: "editingDeadline",
    label: "Modification Deadline",
    category: "event",
    description: "Last date authors can edit their abstract",
    example: "May 30, 2026",
  },
  {
    id: "scoringStartAt",
    label: "Review Opens",
    category: "event",
    description: "Date the committee review window opens",
    example: "June 1, 2026",
  },
  {
    id: "scoringDeadline",
    label: "Review Deadline",
    category: "event",
    description: "Date the committee review window closes",
    example: "June 20, 2026",
  },
  {
    id: "finalFileDeadline",
    label: "Final File Deadline",
    category: "event",
    description: "Deadline for accepted authors to upload the final file",
    example: "July 15, 2026",
  },
];
