import type { VariableDefinition } from "@modules/email/email.types.js";

export const ABSTRACT_EMAIL_VARIABLES: VariableDefinition[] = [
  {
    id: "authorName",
    label: "Author Name",
    category: "abstract",
    description: "First and last name of the submitting author",
    example: "Dr. Ahmed Salah",
  },
  {
    id: "submissionTitle",
    label: "Submission Title",
    category: "abstract",
    description: "Title of the submitted abstract",
    example: "Novel Approaches to Cardiac Imaging",
  },
  {
    id: "submissionStatus",
    label: "Submission Status",
    category: "abstract",
    description: "Current status of the abstract (e.g. Submitted, Accepted)",
    example: "Submitted",
  },
  {
    id: "presentationType",
    label: "Presentation Type",
    category: "abstract",
    description: "Requested or final presentation type",
    example: "Oral Communication",
  },
  {
    id: "submissionCode",
    label: "Submission Code",
    category: "abstract",
    description: "Unique abstract code (assigned after review)",
    example: "AB-001",
  },
  {
    id: "congressName",
    label: "Congress Name",
    category: "event",
    description: "Name of the event/congress",
    example: "Medical Conference 2025",
  },
  {
    id: "platformLink",
    label: "Platform Link",
    category: "links",
    description: "Link to the event on the submission platform",
    example: "https://events.example.com/medical-2025",
  },
  {
    id: "abstractEditLink",
    label: "Abstract Edit Link",
    category: "links",
    description: "Magic link for the author to view/edit their abstract",
    example: "https://events.example.com/medical-2025/abstracts/abc123/token123",
  },
  {
    id: "deadlineDate",
    label: "Deadline Date",
    category: "event",
    description: "Editing deadline for the abstract",
    example: "2025-06-30T23:59:00.000Z",
  },
  {
    id: "committeeComments",
    label: "Committee Comments",
    category: "abstract",
    description: "Comments from the scientific committee (Phase IV)",
    example: "Please revise the methodology section.",
  },
  {
    id: "author_name",
    label: "Author Name (PRD alias)",
    category: "abstract",
    description: "Alias for {{authorName}} using PRD snake_case naming",
    example: "Dr. Ahmed Salah",
  },
  {
    id: "submission_title",
    label: "Submission Title (PRD alias)",
    category: "abstract",
    description: "Alias for {{submissionTitle}} using PRD snake_case naming",
    example: "Novel Approaches to Cardiac Imaging",
  },
  {
    id: "submission_status",
    label: "Submission Status (PRD alias)",
    category: "abstract",
    description: "Alias for {{submissionStatus}} using PRD snake_case naming",
    example: "Submitted",
  },
  {
    id: "presentation_type",
    label: "Presentation Type (PRD alias)",
    category: "abstract",
    description: "Alias for {{presentationType}} using PRD snake_case naming",
    example: "Oral Communication",
  },
  {
    id: "submission_code",
    label: "Submission Code (PRD alias)",
    category: "abstract",
    description: "Alias for {{submissionCode}} using PRD snake_case naming",
    example: "AB-001",
  },
  {
    id: "congress_name",
    label: "Congress Name (PRD alias)",
    category: "event",
    description: "Alias for {{congressName}} using PRD snake_case naming",
    example: "Medical Conference 2025",
  },
  {
    id: "platform_link",
    label: "Platform Link (PRD alias)",
    category: "links",
    description: "Alias for {{platformLink}} using PRD snake_case naming",
    example: "https://events.example.com/medical-2025",
  },
  {
    id: "abstract_edit_link",
    label: "Abstract Edit Link (snake_case alias)",
    category: "links",
    description: "Alias for {{abstractEditLink}} using snake_case naming",
    example: "https://events.example.com/medical-2025/abstracts/abc123/token123",
  },
  {
    id: "deadline_date",
    label: "Deadline Date (PRD alias)",
    category: "event",
    description: "Alias for {{deadlineDate}} using PRD snake_case naming",
    example: "2025-06-30T23:59:00.000Z",
  },
  {
    id: "committee_comments",
    label: "Committee Comments (PRD alias)",
    category: "abstract",
    description: "Alias for {{committeeComments}} using PRD snake_case naming",
    example: "Please revise the methodology section.",
  },
];
