export const ErrorCodes = {
  // Auth (1xxx)
  UNAUTHORIZED: "AUTH_1001",
  INVALID_TOKEN: "AUTH_1002",
  FORBIDDEN: "AUTH_1004",

  // Validation (2xxx)
  VALIDATION_ERROR: "VAL_2001",

  // Resource (3xxx)
  NOT_FOUND: "RES_3001",
  CONFLICT: "RES_3002",
  BAD_REQUEST: "RES_3003",

  // Rate Limit (4xxx)
  RATE_LIMITED: "RATE_4001",

  // Server (5xxx)
  INTERNAL_ERROR: "SRV_5001",
  DATABASE_ERROR: "SRV_5002",

  // Pricing (6xxx)
  EXTRA_CAPACITY_EXCEEDED: "PRC_6001",
  PRICE_MISMATCH: "PRC_6002",
  EXTRA_NOT_AVAILABLE: "PRC_6003",
  INVALID_SPONSORSHIP_CODE: "PRC_6004",
  PRICING_NOT_FOUND: "PRC_6005",

  // Access (7xxx)
  ACCESS_NOT_FOUND: "ACC_7001",
  ACCESS_CAPACITY_EXCEEDED: "ACC_7002",
  ACCESS_TIME_CONFLICT: "ACC_7004",
  ACCESS_PREREQUISITE_MISSING: "ACC_7005",
  ACCESS_NOT_AVAILABLE: "ACC_7006",
  ACCESS_CIRCULAR_DEPENDENCY: "ACC_7007",
  ACCESS_HAS_REGISTRATIONS: "ACC_7008",
  ACCESS_DATE_OUT_OF_BOUNDS: "ACC_7009",
  ACCESS_HAS_SPONSORSHIPS: "ACC_7010",

  // Events (8xxx)
  EVENT_HAS_REGISTRATIONS: "EVT_8000",
  EVENT_NOT_OPEN: "EVT_8001",
  EVENT_FULL: "EVT_8002",
  CAPACITY_BELOW_REGISTERED: "EVT_8003",

  // Registration (8xxx — shared numeric range with Events, use string prefix to disambiguate)
  REGISTRATION_NOT_FOUND: "REG_8001",
  REGISTRATION_ALREADY_EXISTS: "REG_8002",
  REGISTRATION_REFUNDED: "REG_8003",
  REGISTRATION_INVALID_STATUS: "REG_8004",
  REGISTRATION_PAYMENT_REQUIRED: "REG_8005",
  EVENT_CAPACITY_EXCEEDED: "REG_8006",
  REGISTRATION_EDIT_FORBIDDEN: "REG_8007",
  REGISTRATION_ACCESS_REMOVAL_BLOCKED: "REG_8008",
  REGISTRATION_DELETE_BLOCKED: "REG_8009",
  REGISTRATION_VERIFYING_BLOCKED: "REG_8010",
  REGISTRATION_FULLY_SPONSORED_BLOCKED: "REG_8011",
  REGISTRATION_WAIVED_ACCESS_BLOCKED: "REG_8012",

  // Form Validation (9xxx)
  INVALID_FORM_SCHEMA: "FRM_9000",
  FORM_VALIDATION_ERROR: "FRM_9001",
  FORM_FIELD_REQUIRED: "FRM_9002",
  FORM_FIELD_INVALID_FORMAT: "FRM_9003",
  FORM_FIELD_INVALID_TYPE: "FRM_9004",
  FORM_FILE_TOO_LARGE: "FRM_9005",
  FORM_FILE_INVALID_TYPE: "FRM_9006",

  // File Upload (10xxx)
  INVALID_FILE_TYPE: "FIL_10001",
  FILE_TOO_LARGE: "FIL_10002",

  // Reports (11xxx)
  REPORT_GENERATION_FAILED: "RPT_11001",
  EXPORT_FAILED: "RPT_11002",
  EXPORT_TOO_LARGE: "RPT_11003",

  // State Transitions (12xxx)
  INVALID_STATUS_TRANSITION: "STT_12001",
  INVALID_PAYMENT_TRANSITION: "STT_12002",
  EDIT_TOKEN_EXPIRED: "STT_12003",

  // Dependencies (13xxx)
  CLIENT_HAS_DEPENDENCIES: "DEP_13001",

  // Sponsorship (14xxx)
  SPONSORSHIP_NOT_APPLICABLE: "SPO_14001",
  SPONSORSHIP_STATUS_CONFLICT: "SPO_14002",

  // Email (15xxx)
  MJML_COMPILATION_ERROR: "EML_15001",

  // Concurrency (16xxx)
  CONCURRENT_MODIFICATION: "CON_16001",

  // Check-in (17xxx)
  CHECKIN_ALREADY_DONE: "CHK_17001",
  CHECKIN_REGISTRATION_NOT_FOUND: "CHK_17002",
  CHECKIN_ACCESS_NOT_ON_REGISTRATION: "CHK_17003",
  CHECKIN_EVENT_MISMATCH: "CHK_17004",
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];
