/** Compatibility entry point; query implementations are grouped by workflow. */
export {
  buildSponsorshipWhere,
  type SponsorshipListItem,
  listSponsorships,
  type SponsorshipWithUsages,
  getSponsorshipById,
  type SponsorshipWithBatch,
  getSponsorshipByCode,
  getSponsorshipClientId,
  type PendingSponsorshipRow,
  getPendingSponsorships,
  type RegistrationCoverageRow,
  getRegistrationCoverage,
  type LinkedSponsorshipItem,
  getLinkedSponsorships,
} from "./sponsorships-read";
export {
  type AccessItemForOverlap,
  findActiveEventAccess,
  type SponsorshipEventPricing,
  getSponsorshipEventPricing,
  type EventForBatch,
  findEventForBatch,
  findSponsorFormById,
  getActiveSponsorForm,
  getFormSchema,
  type RegistrationForBatch,
  findRegistrationsForBatch,
  insertSponsorshipBatch,
  insertSponsorship,
  sponsorshipCodeExists,
} from "./sponsorships-batch";
export {
  type SponsorshipForMutation,
  findSponsorshipForMutation,
  updateSponsorshipRow,
  deleteSponsorshipRow,
  type SponsorshipForLink,
  findSponsorshipForLink,
  type RegistrationForLink,
  findRegistrationForLink,
  findUsage,
  insertUsage,
  deleteUsage,
  casSetSponsorshipUsed,
  findUsageAmountsByRegistration,
  countUsagesForSponsorship,
  updateRegistrationSettlement,
  type RegistrationSettlementState,
  findRegistrationSettlementState,
  type SponsorshipUnlinkState,
  findSponsorshipUnlinkState,
  type RecalcSponsorship,
  findSponsorshipForRecalc,
  updateUsageAmount,
  type SponsorshipEmailOutboxPayload,
  enqueueSponsorshipEmailOutbox,
} from "./sponsorship-usages";
export {
  type RegistrationRouteGuard,
  getRegistrationForSponsorship,
  type RegistrantSearchRow,
  searchRegistrantsForSponsorship,
} from "./sponsorship-registrants";
export {
  type SponsorshipRow,
  type SponsorshipUsageRow,
  type SponsorshipBatchRow,
  type SponsorshipClientGate,
  type ExistingUsageRow,
} from "./sponsorships-shared";
