/**
 * Condition parity fixtures for the frontends: the hand-written case files
 * the backend evaluators are tested against (in `packages/shared/src`),
 * exported in one documented format so the admin and form repos can run the
 * same cases against their copies.
 *
 * Format `focale.condition-parity/v1`: a JSON object with the fields below and
 * `cases`, one object per line:
 *   { "name": string, "conditions": Condition[], "logic"?: string,
 *     "formData": object, "expected": boolean | "throws" }
 * Call the evaluator named in `call` with (conditions, logic, formData); when
 * `logic` is absent, omit the argument (the evaluator's default applies). A
 * key missing from `formData` means undefined, and a condition without `value`
 * has value undefined. `"throws"` means the evaluator throws.
 */
import { readFileSync } from "node:fs";
import { join } from "node:path";

export const PARITY_FORMAT = "focale.condition-parity/v1";

export interface ParityFixtureSpec {
  /** Output file name under `generated/fixtures/` (without `.json`). */
  id: string;
  /** Source file in `packages/shared/src`. */
  source: string;
  call: string;
  backend: string;
  frontendCopies: string[];
}

export const PARITY_FIXTURES: readonly ParityFixtureSpec[] = [
  {
    id: "field-visibility",
    source: "field-visibility.parity-cases.json",
    call: "evaluateConditions(conditions, logic, formData)",
    backend: "packages/shared/src/field-visibility.ts evaluateConditions (exact port of the form app's evaluator)",
    frontendCopies: [
      "form: src/lib/conditions.ts evaluateConditions (field visibility)",
      "admin: src/features/registrations/utils/conditions.ts evaluateConditions (field visibility)",
    ],
  },
  {
    id: "rule-conditions",
    source: "rule-conditions.parity-cases.json",
    call: "evaluateRuleConditions(conditions, logic, formData)",
    backend: "packages/shared/src/conditions.ts evaluateRuleConditions (pricing rules and access conditions)",
    frontendCopies: ["form: src/lib/pricing-conditions.ts evaluateConditions (pricing preview)"],
  },
];

interface ParityCase {
  name: string;
  conditions: unknown[];
  logic?: string;
  formData: Record<string, unknown>;
  expected: boolean | "throws";
}

function isPlainObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === "object" && !Array.isArray(value);
}

/** Validate a source file and put each case's keys in the documented order. */
export function parseParityCases(sourceName: string, raw: unknown): { description: string; cases: ParityCase[] } {
  const fail = (message: string): never => {
    throw new Error(`${sourceName}: ${message}`);
  };
  if (!isPlainObject(raw)) return fail("expected a JSON object");
  if (typeof raw.description !== "string") return fail("missing description");
  if (!Array.isArray(raw.cases) || raw.cases.length === 0) return fail("missing cases");

  const names = new Set<string>();
  const cases = raw.cases.map((item, index): ParityCase => {
    if (!isPlainObject(item)) return fail(`case ${index} is not an object`);
    const { name, conditions, logic, formData, expected, ...extra } = item;
    if (typeof name !== "string" || name === "") return fail(`case ${index} has no name`);
    if (names.has(name)) return fail(`duplicate case name "${name}"`);
    names.add(name);
    if (Object.keys(extra).length > 0) return fail(`case "${name}" has unknown keys ${Object.keys(extra).join(", ")}`);
    if (!Array.isArray(conditions)) return fail(`case "${name}" conditions must be an array`);
    if (logic !== undefined && typeof logic !== "string") return fail(`case "${name}" logic must be a string`);
    if (!isPlainObject(formData)) return fail(`case "${name}" formData must be an object`);
    if (typeof expected !== "boolean" && expected !== "throws") {
      return fail(`case "${name}" expected must be true, false or "throws"`);
    }
    return { name, conditions, ...(logic === undefined ? {} : { logic }), formData, expected };
  });
  return { description: raw.description, cases };
}

export function renderParityFixture(spec: ParityFixtureSpec, sharedSrcDir: string): string {
  const raw: unknown = JSON.parse(readFileSync(join(sharedSrcDir, spec.source), "utf8"));
  const { description, cases } = parseParityCases(spec.source, raw);
  const header = {
    $comment: `GENERATED by \`pnpm contracts:generate\` from packages/shared/src/${spec.source}. Do not edit.`,
    format: PARITY_FORMAT,
    evaluator: spec.id,
    call: spec.call,
    backend: spec.backend,
    frontendCopies: spec.frontendCopies,
    description,
  };
  const head = JSON.stringify(header, null, 2).slice(0, -2);
  const body = cases.map((item) => `    ${JSON.stringify(item)}`).join(",\n");
  return `${head},\n  "cases": [\n${body}\n  ]\n}\n`;
}
