/**
 * Everything `pnpm contracts:generate` writes to `packages/contracts/generated/`,
 * as (path, content) pairs. Pure apart from reading the parity case sources,
 * and deterministic: sorted names, canonical key order, no timestamps or
 * commit ids, so the CI staleness check only fails on a real change.
 */
import {
  collectContractSchemas,
  findUnrepresentable,
  renderJsonSchemaDocument,
  type SchemaDirection,
  type UnrepresentableEntry,
} from "./json-schema";
import { PARITY_FIXTURES, PARITY_FORMAT, renderParityFixture } from "./fixtures";
import { renderTypeScript, typeNameFor } from "./typescript";

export interface GeneratedFile {
  /** Path relative to `packages/contracts/generated/`. */
  path: string;
  content: string;
}

const DIRECTIONS: readonly SchemaDirection[] = ["input", "output"];

const DIRECTION_NOTES: Record<SchemaDirection, string> = {
  input: "Input side: bodies, queries and params as a client sends them, before the server parses them.",
  output: "Output side: values after the server parses them (defaults filled); response bodies built from these schemas.",
};

export function renderContractArtifacts(sharedSrcDir: string): GeneratedFile[] {
  const entries = collectContractSchemas();
  const files: GeneratedFile[] = [];
  const unrepresentable: UnrepresentableEntry[] = [];

  for (const direction of DIRECTIONS) {
    const document = renderJsonSchemaDocument(direction, entries);
    unrepresentable.push(...findUnrepresentable(direction, document));
    files.push({
      path: `json-schema/contracts.${direction}.json`,
      content: `${JSON.stringify(document, null, 2)}\n`,
    });
    files.push({
      path: `types/contracts.${direction}.ts`,
      content: renderTypeScript(document, [
        "GENERATED by `pnpm contracts:generate` from packages/contracts. Do not edit.",
        DIRECTION_NOTES[direction],
        `Same content as ../json-schema/contracts.${direction}.json: one type per exported`,
        "schema, named without the `Schema` suffix. Dates are ISO 8601 strings.",
      ]),
    });
  }

  for (const spec of PARITY_FIXTURES) {
    files.push({ path: `fixtures/${spec.id}.json`, content: renderParityFixture(spec, sharedSrcDir) });
  }

  const schemas: Record<string, { module: string; type: string; aliasOf?: string }> = {};
  for (const entry of [...entries].sort((a, b) => (a.name < b.name ? -1 : 1))) {
    schemas[entry.name] = {
      module: `packages/contracts/src/${entry.module}.ts`,
      type: typeNameFor(entry.name),
      ...(entry.aliasOf ? { aliasOf: entry.aliasOf } : {}),
    };
  }
  const manifest = {
    $comment: "GENERATED by `pnpm contracts:generate`. Do not edit. CI fails when this folder is stale.",
    files: Object.fromEntries(
      [
        ...DIRECTIONS.flatMap((direction) => [
          [`json-schema/contracts.${direction}.json`, `JSON Schema draft 2020-12, $defs per schema. ${DIRECTION_NOTES[direction]}`],
          [`types/contracts.${direction}.ts`, `TypeScript types of the same schemas (${direction} side).`],
        ]),
        ...PARITY_FIXTURES.map((spec) => [`fixtures/${spec.id}.json`, `${PARITY_FORMAT} cases for ${spec.call}.`]),
      ].sort(([a], [b]) => (a < b ? -1 : 1)),
    ),
    schemas,
    unrepresentable,
  };
  files.push({ path: "manifest.json", content: `${JSON.stringify(manifest, null, 2)}\n` });

  return files.sort((a, b) => (a.path < b.path ? -1 : a.path > b.path ? 1 : 0));
}
